[tool.ruff]
line-length = 100
target-version = "py312"
show-fixes = true

[tool.ruff.format]
exclude = [".git", "__pycache__/**", "venv/**", "api/migrations/**", "api/temp_migrations/**"]

[tool.ruff.lint]
ignore = ["E203", "E402", "E501", "F403", "F405"]