# Generated by Django 4.2.6 on 2023-10-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_course_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
    ]
