# Generated by Django 4.2.6 on 2023-10-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_quic_remove_student_courses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quic',
            new_name='Quiz',
        ),
    ]
