# Generated by Django 4.2.6 on 2023-10-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_instructor_questionmultiplechoice_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionmultiplechoice',
            table='question_multiple_choice',
        ),
        migrations.AlterModelTable(
            name='userresponse',
            table='user_response',
        ),
    ]
