# Generated by Django 4.2.6 on 2023-10-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_questionmultiplechoice_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionmultiplechoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userresponse',
            table=None,
        ),
    ]
