# Generated by Django 4.2.6 on 2023-10-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_questionmultiplechoice_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionmultiplechoice',
            table='api_question_multiple_choice',
        ),
    ]
