# Generated by Django 4.2.6 on 2024-02-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_quizsession_quiz_alter_userresponse_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='quiz_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.quizsession'),
        ),
    ]
