# Generated by Django 4.2.6 on 2024-02-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_userresponse_quiz_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsessionstudent",
            name="quiz_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="api.quizsession",
            ),
        ),
    ]
