# Generated by Django 4.2.6 on 2024-02-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_quizsessionstudent_quiz_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.quizsessionstudent'),
        ),
    ]
