# Generated by Django 4.2.6 on 2024-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_userresponse_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="question_colors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
