# Generated by Django 4.2.6 on 2024-03-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_quizsession_served_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.questionmultiplechoice'),
        ),
    ]
