# Generated by Django 4.2.6 on 2024-03-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_userresponse_student"),
        ("api", "0020_quizsession_current_question"),
    ]

    operations = []
