# Generated by Django 4.2.6 on 2024-05-23 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_quizsession_question_colors"),
        ("api", "0021_merge_20240307_2036"),
    ]

    operations = []
