# Generated by Django 4.2.6 on 2024-06-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_settings_quiz_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsessionstudent",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizsessionstudent",
            name="skip_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="settings",
            name="skip_count_per_student",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="settings",
            name="skip_question",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="settings",
            name="skip_question_logic",
            field=models.TextField(default="random"),
        ),
        migrations.AddField(
            model_name="settings",
            name="skip_question_streak_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="skipped_question",
            field=models.BooleanField(default=False),
        ),
    ]
