# Generated by Django 4.2.6 on 2024-08-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_remove_quizsessionstudent_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="skip_question_percentage",
            field=models.IntegerField(default=0),
        ),
    ]
