# Generated by Django 4.2.6 on 2024-08-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_settings_skip_question_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='skip_question_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
