# Generated by Django 4.2.6 on 2024-08-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_audiofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioFile',
            new_name='InstructorRecordings',
        ),
        migrations.AlterModelTable(
            name='instructorrecordings',
            table='api_instructor_recordings',
        ),
    ]
