# Generated by Django 4.2.6 on 2024-08-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_instructorrecordings_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorRecordings',
        ),
    ]
