# Generated by Django 4.2.6 on 2024-09-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_remove_instructorrecordings_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorrecordings",
            name="transcript",
            field=models.TextField(default=""),
        ),
    ]
