# Generated by Django 4.2.6 on 2024-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_instructorrecordings_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorrecordings",
            name="title",
            field=models.CharField(default="", max_length=250),
        ),
    ]
