# Generated by Django 4.2.6 on 2024-10-02 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_instructorrecordings_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="instructor_recording",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.instructorrecordings",
            ),
        ),
    ]
