# Generated by Django 4.2.6 on 2024-10-04 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_quiz_instructor_recording"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsession",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_in_sessions",
                to="api.questionmultiplechoice",
            ),
        ),
    ]
