# Generated by Django 4.2.6 on 2024-10-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_quizsession_current_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmultiplechoice",
            name="duration",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="questionmultiplechoice",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="api.quiz",
            ),
        ),
    ]
