# Generated by Django 4.2.6 on 2024-10-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_quizsessionquestion_quizsession_served_questions_new"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="quizsessionquestion",
            table="api_quiz_session_question",
        ),
    ]
