# Generated by Django 4.2.6 on 2024-10-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_auto_20241007_2308"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizsession",
            name="served_questions",
        ),
    ]
