# Generated by Django 4.2.6 on 2024-10-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_rename_served_questions_new_quizsession_served_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsession",
            name="served_questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="served_in_sessions",
                through="api.QuizSessionQuestion",
                to="api.questionmultiplechoice",
            ),
        ),
    ]
