# Generated by Django 4.2.6 on 2024-10-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_quizsession_served_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsessionquestion",
            name="unlocked",
            field=models.BooleanField(default=False),
        ),
    ]
