# Generated by Django 4.2.6 on 2024-10-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_quizsessionquestion_unlocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsessionquestion",
            name="extension",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizsessionquestion",
            name="opened_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="quizsessionquestion",
            name="unlocked",
            field=models.BooleanField(default=True),
        ),
    ]
