# Generated by Django 4.2.6 on 2024-10-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_quizsessionquestion_extension_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsessionquestion",
            name="opened_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
