# Generated by Django 4.2.6 on 2024-10-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_alter_quizsessionquestion_opened_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_contact_message",
            },
        ),
    ]
