# Generated by Django 4.2.6 on 2024-11-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_quizsessionquestion_opened_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='timer_duration',
        ),
    ]
