# Generated by Django 4.2.6 on 2024-11-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_remove_settings_timer_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="num_questions",
            field=models.IntegerField(choices=[(3, "Three"), (5, "Five"), (10, "Ten")], default=5),
        ),
        migrations.AddField(
            model_name="quiz",
            name="question_duration",
            field=models.IntegerField(
                choices=[(15, "Fifteen"), (30, "Thirty"), (60, "Sixty")], default=30
            ),
        ),
    ]
