# Generated by Django 4.2.6 on 2024-11-04 22:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_remove_settings_timer_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recording_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="api.instructorrecordings",
                    ),
                ),
            ],
            options={
                "db_table": "api_lecture_summary",
                "ordering": ["-created_at"],
            },
        ),
    ]
