# Generated by Django 4.2.6 on 2024-11-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_auto_20241111_2121"),
        ("api", "0054_lecturesummary"),
    ]

    operations = []
