# Generated by Django 4.2.6 on 2024-11-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_lecturesummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturesummary",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
