# Generated by Django 4.2.6 on 2024-11-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_lecturesummary_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecturesummary",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="lecturesummary",
            name="recording_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summaries",
                to="api.instructorrecordings",
            ),
        ),
        migrations.AlterField(
            model_name="lecturesummary",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
