# Generated by Django 4.2.6 on 2024-11-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_merge_0054_auto_20241111_2121_0054_lecturesummary"),
        ("api", "0056_merge_20241111_2228"),
    ]

    operations = []
