# Generated by Django 4.2.6 on 2024-11-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_rename_recording_id_lecturesummary_recording"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorrecordings",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
