# Generated by Django 4.2.6 on 2024-11-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_remove_quiz_num_questions_and_more"),
        ("api", "0057_instructorrecordings_duration"),
    ]

    operations = []
