# Generated by Django 4.2.6 on 2024-11-22 20:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_merge_20241113_0042"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="QuizSessionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quiz_session_code", models.CharField(max_length=6, unique=True)),
                ("action", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question_multiple_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.questionmultiplechoice"
                    ),
                ),
                (
                    "quiz_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.quizsession"
                    ),
                ),
                (
                    "quiz_session_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.quizsessionstudent"
                    ),
                ),
            ],
            options={
                "db_table": "api_quiz_session_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
