# Generated by Django 4.2.6 on 2024-11-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_merge_20241113_0042"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="settings",
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
