# Generated by Django 4.2.6 on 2024-11-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_alter_quiz_options_quizsessionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsessionlog",
            name="question_multiple_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.questionmultiplechoice",
            ),
        ),
    ]
