# Generated by Django 4.2.6 on 2024-12-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_alter_quizsessionlog_question_multiple_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="settings",
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
