# Generated by Django 4.2.6 on 2024-12-24 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_remove_quiz_settings_delete_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("code", models.TextField(unique=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("allow_joining_until", models.DateField(auto_now_add=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.instructor"
                    ),
                ),
            ],
            options={
                "db_table": "api_course",
            },
        ),
    ]
