# Generated by Django 4.2.6 on 2024-12-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_alter_course_code_alter_course_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
