# Generated by Django 4.2.6 on 2024-12-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_alter_course_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
