# Generated by Django 4.2.6 on 2024-12-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_alter_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorrecordings",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
        migrations.AddField(
            model_name="lecturesummary",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
    ]
