# Generated by Django 4.2.6 on 2024-12-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_instructorrecordings_course_lecturesummary_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorrecordings",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lecturesummary",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
