# Generated by Django 4.2.6 on 2025-01-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_coursestudent"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorrecordings",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
        migrations.AddField(
            model_name="instructorrecordings",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lecturesummary",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
        migrations.AddField(
            model_name="lecturesummary",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
