# Generated by Django 4.2.6 on 2025-01-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_alter_course_allow_joining_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursestudent",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
