# Generated by Django 4.2.6 on 2025-01-25 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_alter_coursestudent_joined_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="allow_joining_until",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
