# Generated by Django 4.2.6 on 2025-01-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_alter_course_allow_joining_until"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="skip_count_per_student",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="skip_question",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="skip_question_logic",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="skip_question_percentage",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="skip_question_streak_count",
        ),
        migrations.RemoveField(
            model_name="quizsessionquestion",
            name="skipped",
        ),
        migrations.RemoveField(
            model_name="quizsessionstudent",
            name="skip_count",
        ),
        migrations.RemoveField(
            model_name="userresponse",
            name="skipped_question",
        ),
    ]
