# Generated by Django 4.2.6 on 2025-02-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_remove_quiz_skip_count_per_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsessionquestion",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="quizsessionstudent",
            name="score",
            field=models.IntegerField(default=-1),
        ),
    ]
