# Generated by Django 4.2.6 on 2024-11-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_lecturesummary"),
        ("api", "0055_remove_quiz_num_questions_and_more"),
    ]

    operations = []
