name: Run Django Tests

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: |
          coverage run --source=. --omit=api/tests/consumer_tests.py manage.py test -v 3
          coverage report --fail-under=65
