name: Flake8 Format and Test


on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  flake8-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: pip install flake8

      - name: Format code with Flake8
        run: flake8
