name: Ruff Lint and Format

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruff
        uses: astral-sh/ruff-action@v3

      - name: Lint
        run: ruff check

      - name: Format
        run: ruff format --check
