name: WebSocket Tests

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run WebSocket Tests
      env:
        DJANGO_SETTINGS_MODULE: hice_backend.settings
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        REDIS: redis
      run: |
        pytest api/tests/consumer_tests.py -v